### PR TITLE
Fix issue with status query log table size growing too large

### LINKED ISSUE #6: Log database table grows huge
The payment checker logs the same request indefinitely at https://github.com/maksuturva/woocommerce_payment_module/blob/master/includes/class-wc-payment-checker-maksuturva.php#L84

There's no checks for if the same request has already been logged or not.

### PR DESCRIPTION
**Pull request by soderluk**
Fixes #6

### CODE REVIEW

File: includes/class-wc-payment-checker-maksuturva.php [hunk 1]
```diff
@@ -154,10 +179,36 @@ public function check_payments( array $payments ) {
...
+		$tbl        = $wpdb->prefix . self::TABLE_NAME;
+		$payment_id = $payment->get_payment_id();
+
+		// First get the results for the payment.
+		$results = $wpdb->get_results( $wpdb->prepare(
+			'SELECT payment_id, date_added, query_count FROM %s WHERE payment_id = %s', $tbl, $payment_id ) );
+
+		// By default we set query count to 1. Loop through any found results and increment the query_count.
+		$query_count = 1;
+		foreach ( $results as $result ) {
```
Comment (kryysler) [inline includes/class-wc-payment-checker-maksuturva.php]: how can there be many results if the table is truncated and then only 1 record is inserted and updated?

Comment (soderluk) [inline includes/class-wc-payment-checker-maksuturva.php]: The `get_results()` function always returns an array. Could use array_pop or something else here as well, but looping through the array is still more safe.

File: includes/class-wc-payment-checker-maksuturva.php [hunk 2]
```diff
@@ -154,10 +179,36 @@ public function check_payments( array $payments ) {
...
+			$query_count += $result->query_count;
+		}
+
+		// If we found anything, e.g. query_count is over 1, update the record and increase the query_count by one.
+		if ( $query_count > 1 ) {
+			$wpdb->update( $tbl, array(
+				'response'    => wp_json_encode( $response ),
+				'query_count' => $query_count,
+			), array(
+					'payment_id' => $payment_id,
```
Comment (kryysler) [inline includes/class-wc-payment-checker-maksuturva.php]: The payment_id is not indexed, will this not be slow:ish when the table size grows?

File: includes/class-wc-payment-checker-maksuturva.php (hunk 1 above)
Comment (kryysler) [inline includes/class-wc-payment-checker-maksuturva.php]: good point

File: includes/class-wc-payment-checker-maksuturva.php [hunk 3]
```diff
@@ -154,10 +179,36 @@ public function check_payments( array $payments ) {
...
-			'payment_id' => $payment->get_payment_id(),
-			'response'   => wp_json_encode( $response ),
-			'date_added' => date( 'Y-m-d H:i:s' ),
-		) ); // Db call ok.
+		$tbl        = $wpdb->prefix . self::TABLE_NAME;
+		$payment_id = $payment->get_payment_id();
+
+		// First get the results for the payment.
+		$results = $wpdb->get_results( $wpdb->prepare(
+			'SELECT payment_id, date_added, query_count FROM %s WHERE payment_id = %s', $tbl, $payment_id ) );
```
Comment (kryysler) [inline includes/class-wc-payment-checker-maksuturva.php]: The payment_id is not indexed, will this not be slow:ish when the table size grows?

File: includes/class-wc-payment-checker-maksuturva.php [hunk 4]
```diff
@@ -52,18 +52,43 @@ class WC_Payment_Checker_Maksuturva {
...
+		// Truncate the table if the current version is below the specified DB version.
+		$version = get_option( WC_Maksuturva::OPTION_DB_VERSION );
+		if ( version_compare( $version, WC_Maksuturva::DB_VERSION ) < 0 ) {
+			self::truncate_table();
+		}
+
 		$tbl = $wpdb->prefix . self::TABLE_NAME;
 
 		$sql = 'CREATE TABLE `' . $tbl . '` (
 		`payment_id` varchar(36) NOT NULL,
```
Comment (kryysler) [inline includes/class-wc-payment-checker-maksuturva.php]: Can the payment_id be unique after the truncate? does dbDelta handle the change?

File: includes/class-wc-payment-checker-maksuturva.php (hunk 3 above)
Comment (soderluk) [inline includes/class-wc-payment-checker-maksuturva.php]: Valid point. Will make the payment_id UNIQUE, so it will also be indexed.

File: includes/class-wc-payment-checker-maksuturva.php (hunk 4 above)
Comment (soderluk) [inline includes/class-wc-payment-checker-maksuturva.php]: It should be able to handle the unique keys. Will make it unique.
